// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AppClientes.Model.Entities;

public partial class Cliente
{
    [Required]
    [RegularExpression(@"^[0-9]+$")]
    public int Id { get; set; }

    [Required]
    [MaxLength(100)]
    public string Nombres { get; set; }

    [Required]
    [MaxLength(100)]
    public string Apellidos { get; set; }

    public DateTime? FechaNac { get; set; }

    [Required]
    [MinLength(13)]
    [MaxLength(13)]
    [RegularExpression(@"^[0-9-]+$")]
    public string Cuit { get; set; }

    [MaxLength(100)]
    public string Domicilio { get; set; }

    [Required]
    [MaxLength(20)]
    [Phone]
    public string Telefono { get; set; }

    [Required]
    [MaxLength(50)]
    [EmailAddress]
    public string Email { get; set; }
}